/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include "interface3.h"

void menuLogin(){
	printf("\n === bienvenido ===");
	printf("\n 1. Registrarse");
	printf("\n 2. Iniciar sesion");
	printf("\n 3. salir");
}

void
gestion_cliente_1(char *host)
{
	CLIENT *clnt1;
	bool_t  *result_1;
	nodo_cliente  objCliente;
	CLIENT *clnt2;
	bool_t  *result_2;

#ifndef	DEBUG
	clnt1 = clnt_create (host, gestion_cliente, gestion_cliente_version_1, "udp");
	if (clnt1 == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	clnt2 = clnt_create (host, gestion_cliente, gestion_cliente_version_1, "udp");
	if (clnt2 == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int ingresar=0;
	do{
		menuLogin();
		printf("\n Digite una opcion:");
		scanf("%d",&ingresar);
		switch (ingresar)
		{
			case 1:

				printf("\n Ingrese su identificacion:");
				scanf("%d",&objCliente.identificacionClnt);
				printf("\n Ingrese el nombre:");
				scanf("%s",objCliente.nombre);
				printf("\n Ingrese el apellido:");
				scanf("%s",objCliente.apellido);
				printf("\n Ingrese el login:");
				scanf("%s",objCliente.login);
				printf("\n Ingrese la contrasenia:");
				scanf("%s",objCliente.contrasenia);

				result_1 =  registrarcliente_1(&objCliente, clnt1);
				if (result_1 == (bool_t *) NULL) {
					clnt_perror (clnt1, "call failed");
				}
				if(*result_1==TRUE){
					printf("\n Registro exitoso!");
				}
				else{
					printf("\n No se pudo registrar el administrador.");
				}
			break;
			case 2:
				printf("\n Ingrese el login:");
				scanf("%s",objCliente.login);
				printf("\n Ingrese la contrasenia:");
				scanf("%s",objCliente.contrasenia);

				result_1 =  enviardatossesioncliente_1(&objCliente, clnt1);
				if (result_1 == (bool_t *) NULL) {
					clnt_perror (clnt1, "call failed");
				}

				if(*result_1==TRUE){
					printf("\n Bienvenido al sistema!");
				}
				else{
					printf("\n ERROR, login o contrasenia incorrecta.");
				}
			break;
			default:
				printf("\n Error, digite una opcion valida!");
			break;
		}


		if(ingresar<1 && ingresar>3){
			printf("\n ERROR, digite una opcion valida!!");
		}
	}while(ingresar !=3);












#ifndef	DEBUG
	clnt_destroy (clnt1);
	clnt_destroy (clnt2);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_cliente_1 (host);
exit (0);
}
